name: Verify version
on:
    release:
        types: [published]
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: pip3 install -r .github/requirements.txt
            - name: Verify version
              run: python3 .github/versions.py
